"""Organization model

Revision ID: 0ff603b1cd9e
Revises: 607659d090e6
Create Date: 2026-01-01 15:15:18.336896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ff603b1cd9e"
down_revision: Union[str, None] = "607659d090e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_user_assigned_staff_id",
        "users",
        "org_members",
        ["assigned_staff_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_assigned_staff_id", "users", type_="foreignkey")
    # ### end Alembic commands ###
