"""UserDashboard model

Revision ID: 155b58d12c01
Revises: d202c3ce4bae
Create Date: 2026-01-01 15:16:44.261145

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "155b58d12c01"
down_revision: Union[str, None] = "d202c3ce4bae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
