"""Added email and password fields for Organization and admin

Revision ID: 1ca0441001be
Revises: 75925de1dd6b
Create Date: 2025-06-27 15:04:41.207370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca0441001be'
down_revision: Union[str, None] = '75925de1dd6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('email', sa.String(), nullable=False))
    op.add_column('admin', sa.Column('hashed_password', sa.String(), nullable=False))
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=True)
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=False))
    op.add_column('organizations', sa.Column('hashed_password', sa.String(), nullable=False))
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.drop_column('organizations', 'hashed_password')
    op.drop_column('organizations', 'email')
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.drop_column('admin', 'hashed_password')
    op.drop_column('admin', 'email')
    # ### end Alembic commands ###
