"""Updated user foreign_key issue

Revision ID: 55773bd84aaa
Revises: 57348f1b013a
Create Date: 2025-07-03 12:42:30.468854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55773bd84aaa'
down_revision: Union[str, None] = '57348f1b013a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
