"""Updated user with dashboard and Created UserDashboad Model

Revision ID: 57348f1b013a
Revises: 0e8f65885f83
Create Date: 2025-07-03 12:34:57.575241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "57348f1b013a"
down_revision: Union[str, None] = "0e8f65885f83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_dashboards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("personal_info", sa.JSON(), nullable=True),
        sa.Column("bio_data", sa.JSON(), nullable=True),
        sa.Column("health_metrics", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_dashboards_id"), "user_dashboards", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_dashboards_id"), table_name="user_dashboards")
    op.drop_table("user_dashboards")
    # ### end Alembic commands ###
