"""initial migration

Revision ID: 607659d090e6
Revises:
Create Date: 2026-01-01 15:14:11.354730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "607659d090e6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("id", sa.UUID(as_uuid=False), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "user_type",
            sa.Enum("ADMIN", "USER", "ORGANIZATION", "ORG_MEMBER", name="usertype"),
            nullable=False,
        ),
        sa.Column("is_admin", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_email"), "admin", ["email"], unique=True)
    op.create_index(op.f("ix_admin_id"), "admin", ["id"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(as_uuid=False), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "user_type",
            sa.Enum("ADMIN", "USER", "ORGANIZATION", "ORG_MEMBER", name="usertype"),
            nullable=True,
        ),
        sa.Column(
            "role",
            sa.Enum("ORG_ADMIN", "DOCTOR", "NURSE", "STAFF", name="orgrole"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_email"), "organizations", ["email"], unique=True
    )
    op.create_index(op.f("ix_organizations_id"), "organizations", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(as_uuid=False), autoincrement=False, nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "user_type",
            sa.Enum("ADMIN", "USER", "ORGANIZATION", "ORG_MEMBER", name="usertype"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "subscription_tier",
            sa.Enum("FREE", "BASIC", "PREMIUM", name="subscriptiontier"),
            nullable=True,
        ),
        sa.Column(
            "currency", sa.Enum("USD", "NGN", "EUR", name="currency"), nullable=True
        ),
        sa.Column("assigned_staff_id", sa.UUID(as_uuid=False), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_staff_id"],
            ["org_members.id"],
            name="fk_user_assigned_staff_id",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "org_members",
        sa.Column("id", sa.UUID(as_uuid=False), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "role",
            sa.Enum("ORG_ADMIN", "DOCTOR", "NURSE", "STAFF", name="orgrole"),
            nullable=True,
        ),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_org_members_email"), "org_members", ["email"], unique=False
    )
    op.create_index(op.f("ix_org_members_id"), "org_members", ["id"], unique=False)
    op.create_index(
        op.f("ix_org_members_username"), "org_members", ["username"], unique=False
    )
    op.create_table(
        "user_dashboards",
        sa.Column("id", sa.UUID(as_uuid=False), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("personal_info", sa.JSON(), nullable=True),
        sa.Column("bio_data", sa.JSON(), nullable=True),
        sa.Column("health_metrics", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_dashboards_id"), "user_dashboards", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_dashboards_id"), table_name="user_dashboards")
    op.drop_table("user_dashboards")
    op.drop_index(op.f("ix_org_members_username"), table_name="org_members")
    op.drop_index(op.f("ix_org_members_id"), table_name="org_members")
    op.drop_index(op.f("ix_org_members_email"), table_name="org_members")
    op.drop_table("org_members")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_id"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_email"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_admin_id"), table_name="admin")
    op.drop_index(op.f("ix_admin_email"), table_name="admin")
    op.drop_table("admin")
    # ### end Alembic commands ###
