"""OrgMember model

Revision ID: 696d1165b0fb
Revises: 0ff603b1cd9e
Create Date: 2026-01-01 15:15:54.913972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "696d1165b0fb"
down_revision: Union[str, None] = "0ff603b1cd9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
