"""Updated OrgMember assigned patients

Revision ID: 6ee8f6138bfb
Revises: 55773bd84aaa
Create Date: 2025-07-03 12:55:54.254326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee8f6138bfb'
down_revision: Union[str, None] = '55773bd84aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
