"""enable multi organization membership

Revision ID: 710bfb02e6c5
Revises: 8fd689550604
Create Date: 2025-10-13 23:08:37.414091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "710bfb02e6c5"
down_revision: Union[str, None] = "8fd689550604"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("org_members_user_id_fkey"), "org_members", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("org_members_organization_id_fkey"), "org_members", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "org_members", "organizations", ["organization_id"], ["id"]
    )
    op.create_foreign_key(None, "org_members", "users", ["user_id"], ["id"])
    op.alter_column(
        "organizations",
        "user_type",
        existing_type=postgresql.ENUM("ADMIN", "USER", "ORGANIZATION", name="usertype"),
        nullable=True,
    )
    op.alter_column(
        "organizations",
        "role",
        existing_type=postgresql.ENUM(
            "ORG_ADMIN", "DOCTOR", "NURSE", "STAFF", name="orgrole"
        ),
        nullable=True,
    )
    op.drop_constraint(
        op.f("user_dashboards_user_id_fkey"), "user_dashboards", type_="foreignkey"
    )
    op.create_foreign_key(None, "user_dashboards", "users", ["user_id"], ["id"])
    op.drop_constraint(op.f("fk_user_assigned_staff_id"), "users", type_="foreignkey")
    op.drop_constraint(op.f("users_organization_id_fkey"), "users", type_="foreignkey")
    op.create_foreign_key(
        "fk_user_assigned_staff_id",
        "users",
        "org_members",
        ["assigned_staff_id"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(None, "users", "organizations", ["organization_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_organization_id_fkey", "users", type_="foreignkey")
    op.drop_constraint("fk_user_assigned_staff_id", "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_organization_id_fkey"),
        "users",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_user_assigned_staff_id"),
        "users",
        "org_members",
        ["assigned_staff_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("user_dashboards_user_id_fkey", "user_dashboards", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_dashboards_user_id_fkey"),
        "user_dashboards",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "organizations",
        "role",
        existing_type=postgresql.ENUM(
            "ORG_ADMIN", "DOCTOR", "NURSE", "STAFF", name="orgrole"
        ),
        nullable=False,
    )
    op.alter_column(
        "organizations",
        "user_type",
        existing_type=postgresql.ENUM("ADMIN", "USER", "ORGANIZATION", name="usertype"),
        nullable=False,
    )
    op.drop_constraint("org_members_organization_id_fkey", "org_members", type_="foreignkey")
    op.drop_constraint("org_members_user_id_fkey", "org_members", type_="foreignkey")
    op.create_foreign_key(
        op.f("org_members_organization_id_fkey"),
        "org_members",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("org_members_user_id_fkey"),
        "org_members",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
