"""Updated OrgMember assigned patients

Revision ID: bdb09abe907a
Revises: 6ee8f6138bfb
Create Date: 2025-07-03 12:57:59.327432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bdb09abe907a"
down_revision: Union[str, None] = "6ee8f6138bfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
