"""Admin model

Revision ID: d202c3ce4bae
Revises: 696d1165b0fb
Create Date: 2026-01-01 15:16:15.831362

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d202c3ce4bae"
down_revision: Union[str, None] = "696d1165b0fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
